kind: CronJob
apiVersion: batch/v1
metadata:
  name: cron-job
  namespace: nginx
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      completions: 2
      parallelism: 2
      template:
        metadata:
          name: cron-job-job
          labels:
            app: nginx-name-job
        spec:
          containers:
            - name: print
              image: busybox:latest
              command: ["sh","-c","echo Hello World"]
          restartPolicy: Never
