kind: Job
apiVersion: batch/v1
metadata:
  name: demo-job
  namespace: nginx
spec:
  completions: 2
  parallelism: 2
  template:
    metadata:
      labels:
        app: job
    spec:
      containers:
        - name: print
          image: busybox:latest
          command: ["sh","-c","echo Hello World"]
      restartPolicy: Never

