kind: Deployment
apiVersion: apps/v1
metadata:
  name: notes-app-deployment
  namespace: notes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-app-pod
  template:
    metadata:
      name: notes-app
      labels:
        app: notes-app-pod
    spec:
      containers:
        - name: app
          image: trainwithshubham/notes-app-k8s
          ports:
            - containerPort: 8000
