kind: CronJob
apiVersion: batch/v1
metadata:
  name: demo-cron-job
  namespace: nginx
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      completions: 1
      parallelism: 1
      template:
        metadata:
          name: cron-job-pod
          labels: 
            app: CronJob
        spec:
          containers:
            - name: printer-container
              image: busybox:latest
              command: ["sh","-c","echo Hello World"]
          restartPolicy: Never
