kind: VerticalPodAutoscaler
apiVersion: autoscaling.k8s.io/v1
metadata:
  name: vpa-notes-app
  namespace: notes-app
spec:
  targetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: notes-app-deployment
  updatePolicy:
    updateMode: "Auto"

